import React, { createContext, useContext, useState } from 'react';

export type Language = 'cs' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number> | string, fallbackEn?: string) => string;
}

const translations: Record<string, { cs: string; en: string }> = {
  // Navigation
  'nav.dashboard': { cs: 'Přehled', en: 'Dashboard' },
  'nav.infrastructure': { cs: 'Infrastruktura', en: 'Infrastructure' },
  'nav.websites': { cs: 'Weby & HTTP', en: 'Websites & HTTP' },
  'nav.status-pages': { cs: 'Status Stránky', en: 'Status Pages' },
  'nav.incidents': { cs: 'Incidenty', en: 'Incidents' },
  'nav.insights': { cs: 'AI Insights', en: 'System Insights' },
  'nav.reports': { cs: 'SLA Výkazy', en: 'Reports & SLA' },
  'nav.users': { cs: 'Uživatelé', en: 'Users' },
  'nav.api-agents': { cs: 'API & Agenti', en: 'API & Agents' },
  'nav.settings': { cs: 'Nastavení', en: 'Settings' },

  // Common UI
  'common.loading': { cs: 'Načítání dat...', en: 'Loading data...' },
  'common.saving': { cs: 'Ukládám…', en: 'Saving…' },
  'common.error': { cs: 'Chyba při načítání', en: 'Error loading data' },
  'common.save': { cs: 'Uložit změny', en: 'Save Changes' },
  'common.cancel': { cs: 'Zrušit', en: 'Cancel' },
  'common.delete': { cs: 'Smazat', en: 'Delete' },
  'common.edit': { cs: 'Upravit', en: 'Edit' },
  'common.search': { cs: 'Hledat...', en: 'Search...' },
  'common.all': { cs: 'Vše', en: 'All' },
  'common.online': { cs: 'Online', en: 'Online' },
  'common.offline': { cs: 'Offline', en: 'Offline' },
  'common.warning': { cs: 'Varování', en: 'Warning' },
  'common.healthy': { cs: 'V pořádku', en: 'Healthy' },
  'common.unknown': { cs: 'Neznámý', en: 'Unknown' },
  'common.actions': { cs: 'Akce', en: 'Actions' },
  'common.name': { cs: 'Název', en: 'Name' },
  'common.status': { cs: 'Stav', en: 'Status' },
  'common.target': { cs: 'Cíl', en: 'Target' },
  'common.type': { cs: 'Typ', en: 'Type' },
  'common.category': { cs: 'Kategorie', en: 'Category' },
  'common.response': { cs: 'Odezva', en: 'Latency' },
  'common.last_check': { cs: 'Poslední kontrola', en: 'Last Check' },
  'common.last_change': { cs: 'Poslední změna stavu', en: 'Last Status Change' },
  'common.uptime': { cs: 'Uptime', en: 'Uptime' },
  'common.cpu': { cs: 'Využití CPU', en: 'CPU Usage' },
  'common.ram': { cs: 'Využití RAM', en: 'RAM Usage' },
  'common.hdd': { cs: 'Využití disku', en: 'Disk Usage' },
  'common.details': { cs: 'Detaily', en: 'Details' },
  'common.confirm': { cs: 'Potvrdit', en: 'Confirm' },
  'common.refresh': { cs: 'Obnovit', en: 'Refresh' },
  'common.login_required': { cs: 'Vyžaduje přihlášení', en: 'Login Required' },
  'common.admin_only': { cs: 'Pouze pro administrátory', en: 'Admin Only' },
  'common.open_details': { cs: 'Otevřít detail', en: 'Open Details' },
  'common.back': { cs: 'Zpět', en: 'Back' },
  'common.close': { cs: 'Zavřít', en: 'Close' },
  'common.create': { cs: 'Vytvořit', en: 'Create' },
  'common.yes': { cs: 'Ano', en: 'Yes' },
  'common.no': { cs: 'Ne', en: 'No' },

  // Buttons & Status Labels
  'btn.login': { cs: 'Přihlásit se', en: 'Log In' },
  'btn.logout': { cs: 'Odhlásit se', en: 'Log Out' },
  'btn.save': { cs: 'Uložit změny', en: 'Save Changes' },
  'btn.test': { cs: 'Odeslat testovací notifikaci', en: 'Send Test Notification' },
  'btn.collapse': { cs: 'Sbalit navigaci', en: 'Collapse Sidebar' },
  'btn.expand': { cs: 'Rozbalit navigaci', en: 'Expand Sidebar' },
  'status.healthy': { cs: 'Všechny systémy v pořádku', en: 'All Systems Operational' },
  'status.degraded': { cs: 'Zhoršená latence / Výpadek', en: 'Degraded Performance / Outage' },
  'status.down': { cs: 'Detekován výpadek', en: 'Outage Detected' },

  // Banner
  'banner.live_data': { cs: 'Živá data z databáze', en: 'Live Database Metrics' },
  'banner.live_data_desc': { cs: 'Data se automaticky obnovují každých 10s přímo z MySQL/PostgreSQL backendu.', en: 'Metrics auto-refresh every 10s directly from MySQL/PostgreSQL backend.' },
  'banner.status_offline': { cs: 'Backend /status je nedostupný (HTTP 500 nebo chyba databáze)', en: 'Backend /status is unavailable (HTTP 500 or database error)' },

  // Dashboard
  'dashboard.loading_monitors': { cs: 'Načítám monitory…', en: 'Loading monitors…' },
  'dashboard.loading_uptime': { cs: 'Načítám historii dostupnosti…', en: 'Loading uptime history…' },
  'dashboard.title': { cs: 'Status Overview', en: 'Status Overview' },
  'dashboard.subtitle': { cs: 'Přehled všech vašich monitorovaných služeb, domén a serverů v reálném čase.', en: 'Real-time overview of all monitored services, domains, and servers.' },
  'dashboard.total_monitors': { cs: 'Monitorů celkem', en: 'Total Monitors' },
  'dashboard.monitors_hint': { cs: '{healthy} běží · {down} výpadků', en: '{healthy} running · {down} outages' },
  'dashboard.healthy_pct': { cs: 'Zdravých', en: 'Healthy' },
  'dashboard.healthy_hint': { cs: 'Měřící uzly v pořádku', en: 'Monitoring nodes OK' },
  'dashboard.avg_response': { cs: 'Průměrná odezva', en: 'Average Latency' },
  'dashboard.avg_response_hint': { cs: 'Měřeno ze všech sond', en: 'Measured across all probes' },
  'dashboard.uptime_30d': { cs: 'Uptime (30 dní)', en: '30-Day Uptime' },
  'dashboard.uptime_hint': { cs: 'Global SLA target: 99.9 %', en: 'Global SLA target: 99.9%' },
  'dashboard.filter_all': { cs: 'Vše', en: 'All' },
  'dashboard.filter_online': { cs: 'Online', en: 'Online' },
  'dashboard.filter_warning': { cs: 'Varování', en: 'Warning' },
  'dashboard.filter_offline': { cs: 'Offline', en: 'Offline' },
  'dashboard.search_placeholder': { cs: 'Hledat monitory…', en: 'Search monitors…' },
  'dashboard.recent_alerts': { cs: 'Poslední alerty', en: 'Recent Alerts' },
  'dashboard.all_healthy_title': { cs: 'Všechny sledované služby fungují 100% v pořádku', en: 'All monitored services are operating normally' },
  'dashboard.all_healthy_desc': { cs: 'Všechny systémy a domény OK', en: 'All systems and domains OK' },
  'dashboard.availability_history': { cs: 'Historie dostupnosti sledovaných služeb', en: 'Monitored Services Availability History' },
  'dashboard.availability_30d': { cs: 'Sledovaná dostupnost v čase (posledních 30 dní)', en: 'Tracked availability over time (last 30 days)' },
  'dashboard.outage_title': { cs: 'Výpadek služby', en: 'Service Outage' },
  'dashboard.high_latency': { cs: 'Zvýšená latence', en: 'Increased Latency' },
  'dashboard.whole_infra': { cs: 'Celá infrastruktura', en: 'Entire infrastructure' },
  'dashboard.monitors_card_title': { cs: 'Sledované Monitory & Služby', en: 'Monitored Services' },
  'dashboard.ongoing_outage': { cs: 'Probíhající výpadek', en: 'Ongoing outage' },
  'dashboard.no_outages': { cs: 'Všechny systémy bez výpadku', en: 'All systems without outage' },
  'dashboard.infra_health': { cs: 'Zdraví infrastruktury', en: 'Infrastructure Health' },
  'common.paused': { cs: 'Paused', en: 'Paused' },
  'common.maintenance': { cs: 'Údržba', en: 'Maintenance' },
  'dashboard.full_report': { cs: 'Celý report', en: 'Full Report' },
  'dashboard.no_monitors': { cs: 'Žádný monitor neodpovídá filtru.', en: 'No monitors match the filter.' },

  // Infrastructure
  'infra.title': { cs: 'Správa Infrastruktury & Zařízení', en: 'Infrastructure & Device Management' },
  'infra.subtitle': { cs: 'Kompletní přehled sledovaných serverů, routerů (OpenWrt), herních portů (Minecraft), hlasových služeb (TeamSpeak) a webů.', en: 'Complete overview of monitored servers, routers (OpenWrt), game ports (Minecraft), voice services (TeamSpeak), and websites.' },
  'infra.add_agent': { cs: 'Přidat nový monitor', en: 'Add New Monitor' },
  'infra.load_error': { cs: 'Seznam zařízení se nepodařilo načíst.', en: 'Failed to load the device list.' },
  'infra.admin_required': { cs: 'Pro přidávání a úpravu monitorů musíte mít roli administrátora.', en: 'You must have the administrator role to add or edit monitors.' },
  'infra.name_target_required': { cs: 'Zadejte název a cílovou adresu monitoru.', en: 'Enter the monitor name and target address.' },
  'infra.save_failed_http': { cs: 'Uložení selhalo (HTTP {status}).', en: 'Save failed (HTTP {status}).' },
  'infra.save_failed_network': { cs: 'Uložení selhalo - zkontrolujte připojení.', en: 'Save failed - check your connection.' },
  'infra.edit_monitor_num': { cs: 'Úprava monitoru #{id}', en: 'Editing monitor #{id}' },
  'infra.add_monitor_title': { cs: 'Přidat nový monitor / zařízení', en: 'Add New Monitor / Device' },
  'infra.add_monitor_subtitle': { cs: 'Plné nastavení parametrů, profilů služeb, 2FA/Remote Actions a limitů', en: 'Full configuration of parameters, service profiles, 2FA/Remote Actions, and thresholds' },
  'infra.tab_general': { cs: '1. Základní & Typ', en: '1. General & Type' },
  'infra.tab_metrics': { cs: '2. Sekce Dashboardu', en: '2. Dashboard Sections' },
  'infra.tab_advanced': { cs: '3. Rozšíření & Agent', en: '3. Advanced & Agent' },
  'infra.tab_alerts': { cs: '4. Limity & Notifikace', en: '4. Thresholds & Notifications' },
  'infra.save_success': { cs: 'Monitor byl úspěšně uložen!', en: 'Monitor saved successfully!' },
  'infra.type_label': { cs: 'Typ monitoringu / Služby', en: 'Monitoring / Service Type' },
  'infra.type_web': { cs: 'Web (HTTP/S)', en: 'Web (HTTP/S)' },
  'infra.type_web_desc': { cs: 'Portál, TLS, cPanel stats', en: 'Portal, TLS, cPanel stats' },
  'infra.type_minecraft': { cs: 'Minecraft Server', en: 'Minecraft Server' },
  'infra.type_minecraft_desc': { cs: 'Java 25565 / RCON TPS', en: 'Java 25565 / RCON TPS' },
  'infra.type_teamspeak': { cs: 'TeamSpeak 3', en: 'TeamSpeak 3' },
  'infra.type_teamspeak_desc': { cs: 'Voice 9987, Query 10011', en: 'Voice 9987, Query 10011' },
  'infra.type_openwrt': { cs: 'OpenWrt Router', en: 'OpenWrt Router' },
  'infra.type_openwrt_desc': { cs: 'ubus Agent & Remote Actions', en: 'ubus Agent & Remote Actions' },
  'infra.type_vps': { cs: 'VPS Agent', en: 'VPS Agent' },
  'infra.type_vps_desc': { cs: 'Agent zátěže & procesů', en: 'Load & process agent' },
  'infra.type_discord': { cs: 'Discord Bot', en: 'Discord Bot' },
  'infra.type_discord_desc': { cs: 'Bot WebSocket / Guild API', en: 'Bot WebSocket / Guild API' },
  'infra.display_name': { cs: 'Zobrazovaný název', en: 'Display Name' },
  'infra.display_name_placeholder': { cs: 'Např. Blood Kings Wowko nebo Schlehofer.eu', en: 'E.g. Blood Kings Wowko or Schlehofer.eu' },
  'infra.new_category': { cs: 'Vytvořit novou kategorii...', en: 'Create new category...' },
  'infra.new_category_placeholder': { cs: 'Zadejte název nové kategorie...', en: 'Enter the new category name...' },
  'infra.target_label': { cs: 'Cíl (URL / Hostname / IP / Guild ID)', en: 'Target (URL / Hostname / IP / Guild ID)' },
  'infra.port_label': { cs: 'Port', en: 'Port' },
  'infra.metric_response_breakdown': { cs: 'Rozpad doby odezvy (DNS lookup, Connect, TLS handshake, TTFB)', en: 'Latency breakdown (DNS lookup, Connect, TLS handshake, TTFB)' },
  'infra.metric_ssl': { cs: 'SSL Certifikát a stav TLS 1.3', en: 'SSL Certificate and TLS 1.3 status' },
  'infra.metric_headers': { cs: 'HTTP hlavičky (Server, Content-Type, CSP)', en: 'HTTP headers (Server, Content-Type, CSP)' },
  'infra.recommended': { cs: 'Doporučeno', en: 'Recommended' },
  'infra.metric_health_score': { cs: 'Health Score (Skóre zdraví 0-100)', en: 'Health Score (0-100)' },
  'infra.metric_ts_process': { cs: 'TeamSpeak proces & zátěž', en: 'TeamSpeak process & load' },
  'infra.metric_ts_service': { cs: 'Služba (sloty, kanály, skupiny serveru)', en: 'Service (slots, channels, server groups)' },
  'infra.metric_clients_chart': { cs: 'Graf klientů (24h historie)', en: 'Client chart (24h history)' },
  'infra.metric_voice_quality': { cs: 'Kvalita hlasu & ztráta paketů', en: 'Voice quality & packet loss' },
  'infra.metric_ports': { cs: 'Porty (Voice 9987, Query 10011, FileTransfer 30033)', en: 'Ports (Voice 9987, Query 10011, FileTransfer 30033)' },
  'infra.metric_license': { cs: 'Licence a verze serveru', en: 'Server license and version' },
  'infra.metrics_auto': { cs: 'Pro tento typ služby jsou automaticky povoleny všechny standardní telemetrické metriky.', en: 'All standard telemetry metrics are automatically enabled for this service type.' },
  'infra.web_settings': { cs: 'Nastavení Webu & cPanelu', en: 'Website & cPanel Settings' },
  'infra.cpanel_url': { cs: 'cPanel Stats API URL (volitelné)', en: 'cPanel Stats API URL (optional)' },
  'infra.cpanel_url_hint': { cs: 'Sledování reálného zátížení hostingu (Disk, RAM, CPU, MySQL) přes nahraný soubor cpanel_stats.php s vaším klíčem.', en: 'Tracks real hosting resource usage (Disk, RAM, CPU, MySQL) via the uploaded cpanel_stats.php file with your key.' },
  'infra.body_keyword': { cs: 'Ověření obsahu odpovědi (Body Keyword - volitelné)', en: 'Response body verification (Body Keyword - optional)' },
  'infra.body_keyword_hint': { cs: 'Kontrola ověří, že tělo HTTP odpovědi obsahuje tento řetězec. Pokud chybí, vyhodnotí výpadek.', en: 'The check verifies the HTTP response body contains this string. If missing, it is evaluated as an outage.' },
  'infra.ts3_settings': { cs: 'TeamSpeak 3 ServerQuery & Porty', en: 'TeamSpeak 3 ServerQuery & Ports' },
  'infra.sq_user': { cs: 'ServerQuery Uživatel', en: 'ServerQuery User' },
  'infra.sq_password': { cs: 'ServerQuery Heslo', en: 'ServerQuery Password' },
  'infra.ft_port': { cs: 'FileTransfer Port (výchozí 30033)', en: 'FileTransfer Port (default 30033)' },
  'infra.rcon_settings': { cs: 'Minecraft RCON Příkazové Rozhraní', en: 'Minecraft RCON Command Interface' },
  'infra.rcon_port': { cs: 'RCON Port (výchozí 25575)', en: 'RCON Port (default 25575)' },
  'infra.rcon_password': { cs: 'RCON Heslo', en: 'RCON Password' },
  'infra.rcon_hint': { cs: 'RCON umožňuje dotazovat příkaz "tps" na serveru Spigot/Paper/BungeeCord pro přesný výpočet lagů (TPS).', en: 'RCON allows querying the "tps" command on Spigot/Paper/BungeeCord servers for accurate lag (TPS) readings.' },
  'infra.no_agent_detected': { cs: 'Zatím nebyl detekován žádný aktivní OpenWrt agent na cílové IP/doméně.', en: 'No active OpenWrt agent has been detected on the target IP/domain yet.' },
  'infra.needs_install': { cs: 'Vyžaduje instalaci ⚠️', en: 'Needs installation ⚠️' },
  'infra.remote_actions_title': { cs: 'OpenWrt Remote Actions', en: 'OpenWrt Remote Actions' },
  'infra.remote_actions_desc': { cs: 'Potvrzovací příkazy (reboot routeru, restart WAN, WireGuard) chráněné HMAC-SHA256', en: 'Confirmation commands (router reboot, WAN restart, WireGuard) protected by HMAC-SHA256' },
  'infra.enable_remote_actions': { cs: 'Povolit Remote Actions pro tento router', en: 'Enable Remote Actions for this router' },
  'infra.remote_actions_off_hint': { cs: 'Ve výchozím stavu VYPNUTO. Bez zaškrtnutí server nikdy nezařadí žádnou vzdálenou akci do fronty pro tento konkrétní monitor, bez ohledu na požadavky.', en: 'OFF by default. Without checking this, the server will never queue a remote action for this monitor, regardless of requests.' },
  'infra.allowed_actions_title': { cs: 'Povolené vzdálené akce (OBĚ strany musí souhlasit):', en: 'Allowed remote actions (BOTH sides must agree):' },
  'infra.action_restart_wan': { cs: 'Restartovat WAN', en: 'Restart WAN' },
  'infra.action_restart_wg': { cs: 'Restartovat WireGuard (wg0)', en: 'Restart WireGuard (wg0)' },
  'infra.action_reboot': { cs: 'Restartovat celý router', en: 'Reboot entire router' },
  'infra.action_renew_dhcp': { cs: 'Obnovit DHCP nájem na WAN', en: 'Renew DHCP lease on WAN' },
  'infra.action_pppoe': { cs: 'Znovu připojit PPPoE', en: 'Reconnect PPPoE' },
  'infra.action_restart_service': { cs: 'Restartovat službu', en: 'Restart service' },
  'infra.one_time_install': { cs: 'Jednorázová instalace OpenWrt agenta', en: 'One-time OpenWrt agent installation' },
  'infra.copied_to_clipboard': { cs: 'Příkaz zkopírován do schránky!', en: 'Command copied to clipboard!' },
  'infra.copy_command': { cs: 'Kopírovat příkaz', en: 'Copy Command' },
  'infra.monitored_processes': { cs: 'Sledované procesy (čárkou oddělené)', en: 'Monitored processes (comma-separated)' },
  'infra.monitored_processes_hint': { cs: 'Zadejte názvy procesů, které má agent hlídat. Pokud některý nepoběží, monitor bude označen jako DOWN.', en: 'Enter the process names the agent should watch. If any of them stop running, the monitor will be marked as DOWN.' },
  'infra.notifications_title': { cs: 'Notifikace & Výstražné Limity Agenta', en: 'Agent Notifications & Alert Thresholds' },
  'infra.email_on_outage': { cs: 'Zasílat e-mailové notifikace při výpadku', en: 'Send email notifications on outage' },
  'infra.sms_on_outage': { cs: 'Zasílat SMS notifikace při výpadku', en: 'Send SMS notifications on outage' },
  'infra.timeout_s': { cs: 'Timeout (s)', en: 'Timeout (s)' },
  'infra.cpu_limit': { cs: 'CPU Limit (%)', en: 'CPU Limit (%)' },
  'infra.ram_limit': { cs: 'RAM Limit (%)', en: 'RAM Limit (%)' },
  'infra.hdd_limit': { cs: 'HDD Limit (%)', en: 'HDD Limit (%)' },
  'infra.threshold_hint': { cs: 'Zadejte hodnoty zátěže (v %), při jejichž překročení vám agent zašle varovnou notifikaci.', en: 'Enter load values (in %) above which the agent will send you a warning notification.' },
  'infra.maintenance_title': { cs: 'Režim Údržby & Poznámky', en: 'Maintenance Mode & Notes' },
  'infra.enable_maintenance': { cs: 'Aktivovat režim plánované údržby', en: 'Enable scheduled maintenance mode' },
  'infra.maintenance_desc_label': { cs: 'Popis údržby (zobrazí se uživatelům)', en: 'Maintenance description (shown to users)' },
  'infra.internal_notes': { cs: 'Interní poznámky k monitoru', en: 'Internal monitor notes' },
  'infra.internal_notes_placeholder': { cs: 'Poznámky pro týmové administrátory...', en: 'Notes for team administrators...' },
  'infra.save_monitor_btn': { cs: 'Uložit monitor a nastavení', en: 'Save Monitor & Settings' },
  'infra.search_placeholder': { cs: 'Hledat router, Minecraft, TeamSpeak nebo web...', en: 'Search router, Minecraft, TeamSpeak, or web...' },
  'infra.loading_devices': { cs: 'Načítám zařízení…', en: 'Loading devices…' },
  'infra.open_diagnostics': { cs: 'Otevřít detailní diagnostiku', en: 'Open Detailed Diagnostics' },
  'infra.device_type': { cs: 'Typ zařízení / Protokol', en: 'Device Type / Protocol' },
  'infra.agent_version': { cs: 'Telemetrický Agent & Verze', en: 'Telemetry Agent & Version' },
  'infra.agent_installed': { cs: 'Nainstalován a aktivní', en: 'Installed and active' },
  'infra.no_agent_ping': { cs: 'Bez agenta (Aktivní Ping)', en: 'No agent (Active Ping)' },
  'infra.active_since': { cs: 'Aktivní', en: 'Active' },
  'infra.os': { cs: 'Operační systém', en: 'Operating System' },
  'infra.time_since_change': { cs: 'Doba od poslední změny stavu', en: 'Time since last status change' },
  'infra.select_device': { cs: 'Vyberte zařízení ze seznamu vlevo.', en: 'Select a device from the list on the left.' },
  'infra.tabs_all': { cs: 'Všechny uzly', en: 'All Nodes' },
  'infra.tabs_vps': { cs: 'Linux / VPS Servery', en: 'Linux / VPS Servers' },
  'infra.tabs_teamspeak': { cs: 'TeamSpeak 3', en: 'TeamSpeak 3' },
  'infra.tabs_minecraft': { cs: 'Minecraft Servery', en: 'Minecraft Servers' },
  'infra.tabs_openwrt': { cs: 'OpenWrt / Routery', en: 'OpenWrt / Routers' },
  'infra.clients_online': { cs: 'Připojení klienti', en: 'Connected Clients' },
  'infra.players_online': { cs: 'Hráči online', en: 'Players Online' },
  'infra.open_detail': { cs: 'Otevřít detail', en: 'Open Details' },

  // Asset Detail
  'asset.loading': { cs: 'Načítám detail zařízení a diagnostické metriky…', en: 'Loading device detail and diagnostic metrics…' },
  'asset.back': { cs: 'Zpět na infrastrukturální přehled', en: 'Back to Infrastructure Overview' },
  'asset.tab_overview': { cs: 'Přehled & Výkon', en: 'Overview & Performance' },
  'asset.tab_processes': { cs: 'Procesy serveru', en: 'Server Processes' },
  'asset.tab_processes_short': { cs: 'Procesy', en: 'Processes' },
  'asset.tab_services': { cs: 'Služby & Certifikáty', en: 'Services & Certificates' },
  'asset.tab_events': { cs: 'Události', en: 'Events' },
  'asset.tab_history': { cs: 'Historie měření', en: 'Metrics History' },
  'asset.tab_actions': { cs: 'Vzdálené akce (Remote Actions)', en: 'Remote Actions' },
  'asset.smart_status': { cs: 'Stav SMART / S.M.A.R.T. Disku', en: 'SMART / Disk Health Status' },
  'asset.edit_monitor': { cs: 'Upravit monitor', en: 'Edit Monitor' },
  'asset.proc_name': { cs: 'Název procesu / Příkaz', en: 'Process Name / Command' },
  'asset.proc_cpu': { cs: 'Zátěž CPU (%)', en: 'CPU Usage (%)' },
  'asset.proc_ram': { cs: 'Využití paměti (MB)', en: 'Memory Usage (MB)' },
  'asset.mem_usage': { cs: 'Spotřeba RAM', en: 'RAM Consumption' },
  'asset.process_load': { cs: 'Zátěž procesů serveru ({name})', en: 'Server Process Load ({name})' },
  'asset.process_load_desc': { cs: 'Aktuálně spotřebovávaná paměť RAM a zátěž procesoru.', en: 'Currently consumed RAM and CPU load.' },
  'asset.cpanel_no_agent': { cs: 'Tenhle monitor nemá VPS agenta pro výpis jednotlivých procesů - hostuje se na cPanelu, kde je k dispozici jen souhrnné využití zdrojů:', en: 'This monitor has no VPS agent for listing individual processes - it is hosted on cPanel, where only aggregate resource usage is available:' },
  'asset.no_processes_db': { cs: 'Pro tento uzel nejsou v databázi evidovány žádné samostatné podprocesy.', en: 'No individual subprocesses are recorded in the database for this node.' },
  'asset.no_processes': { cs: 'Žádná data o procesech nejsou k dispozici.', en: 'No process data available.' },
  'asset.services_title': { cs: 'Stav Služeb & Šifrovací Certifikáty', en: 'Service Status & Encryption Certificates' },
  'asset.services_desc': { cs: 'Stav protokolů a šifrovacích certifikátů.', en: 'Status of protocols and encryption certificates.' },
  'asset.ssl_cert': { cs: 'TLS/SSL Certifikát', en: 'TLS/SSL Certificate' },
  'asset.ssl_not_wired': { cs: 'Kontrola certifikátu zatím není napojená', en: 'Certificate check is not wired up yet' },
  'asset.proto_router': { cs: 'OpenWrt Router telemetrie (ubus / Linux agent bez TLS)', en: 'OpenWrt Router telemetry (ubus / Linux agent without TLS)' },
  'asset.proto_minecraft': { cs: 'Minecraft Java socket (port 25565 bez TLS vrstvy)', en: 'Minecraft Java socket (port 25565, no TLS layer)' },
  'asset.proto_teamspeak': { cs: 'TeamSpeak 3 UDP Voice socket bez TLS vrstvy', en: 'TeamSpeak 3 UDP Voice socket without TLS layer' },
  'asset.proto_none': { cs: 'Protokol nepoužívá SSL/TLS vrstvu', en: 'Protocol does not use an SSL/TLS layer' },
  'asset.ssl_expiry_unread': { cs: 'Datum expirace certifikátu se zatím z monitoru nečte.', en: 'Certificate expiry date is not yet read from the monitor.' },
  'asset.service_status': { cs: 'Stav Služby', en: 'Service Status' },
  'asset.smart_no_data': { cs: 'Nejsou dostupná data (agent SMART nehlásí).', en: 'No data available (SMART agent not reporting).' },
  'asset.smart_desc': { cs: 'Sledování opotřebení NVMe buněk, zaoceánovaných chyb a reallocated sektorů z rozhraní smartctl.', en: 'Tracking NVMe cell wear, uncorrectable errors, and reallocated sectors via the smartctl interface.' },
  'asset.svc_name': { cs: 'Služba', en: 'Service' },
  'asset.svc_type': { cs: 'Typ', en: 'Type' },
  'asset.svc_port': { cs: 'Port', en: 'Port' },
  'asset.svc_confidence': { cs: 'Spolehlivost detekce', en: 'Detection Confidence' },
  'asset.no_services': { cs: 'Žádné detekované služby.', en: 'No discovered services.' },
  'asset.trigger_action': { cs: 'Spustit vzdálenou akci', en: 'Trigger Remote Action' },
  'asset.actions_title': { cs: 'Správa akcí a přehled', en: 'Actions Management & Overview' },
  'asset.edit_monitor_title': { cs: 'Upravit nastavení monitoru', en: 'Edit Monitor Settings' },
  'asset.events_history': { cs: 'Historie událostí & Protokol měření ({name})', en: 'Event History & Measurement Log ({name})' },
  'asset.events_history_desc': { cs: 'Záznamy kontrol, detekovaných služeb a změny stavu v čase.', en: 'Records of checks, discovered services, and status changes over time.' },
  'asset.summary_title': { cs: 'Souhrn & Diagnostika', en: 'Summary & Diagnostics' },
  'asset.summary_desc': { cs: 'Živý stav měření z databáze', en: 'Live measurement status from the database' },
  'asset.params_title': { cs: 'Parametry monitoru / serveru', en: 'Monitor / Server Parameters' },
  'asset.recent_events': { cs: 'Poslední události', en: 'Recent Events' },
  'asset.no_agent_cpanel_hint': { cs: 'Bez VPS agenta - podrobnosti o zdrojích cPanelu jsou na záložce Procesy.', en: 'No VPS agent - cPanel resource details are on the Processes tab.' },
  'asset.no_agent_processes': { cs: 'Zatím není připojen agent pro výpis procesů.', en: 'No agent connected yet for listing processes.' },
  'asset.process': { cs: 'Proces', en: 'Process' },
  'asset.detected_services': { cs: 'Detekované Služby / Porty', en: 'Discovered Services / Ports' },
  'asset.no_related_services': { cs: 'Žádné navázané podslužby.', en: 'No related sub-services.' },
  'asset.charts_load_error': { cs: 'Grafy se nepodařilo načíst', en: 'Failed to load charts' },
  'asset.no_chart_data': { cs: 'Data pro tento monitor nejsou v databázi k dispozici', en: 'No data is available in the database for this monitor' },
  'asset.no_chart_data_desc': { cs: 'Nebyla nalezena žádná naměřená historie časových řad pro zadaný rozsah {range}.', en: 'No measured time-series history was found for the selected range {range}.' },
  'common.na': { cs: 'N/A', en: 'N/A' },
  'common.protocol': { cs: 'Protokol', en: 'Protocol' },
  'asset.ts3_clients': { cs: 'Připojení klienti TS3', en: 'Connected TS3 Clients' },
  'asset.ts3_clients_value': { cs: '{online} / {max} uživatelů', en: '{online} / {max} users' },
  'asset.ts3_serverquery': { cs: 'TeamSpeak 3 ServerQuery', en: 'TeamSpeak 3 ServerQuery' },
  'asset.ts3_serverquery_value': { cs: '{online} / {max} uživatelů online (Port 9987/8200)', en: '{online} / {max} users online (Port 9987/8200)' },
  'asset.summary_text': { cs: 'Monitor {name} ({type}) běží na cíli {target}. Metriky se pravidelně ukládají a vyhodnocují v databázi.', en: 'Monitor {name} ({type}) runs against target {target}. Metrics are stored and evaluated in the database on a regular basis.' },
  'asset.all_tests_ok': { cs: 'Všechny testy OK', en: 'All tests OK' },
  'asset.outage_detected': { cs: 'Detekován výpadek', en: 'Outage detected' },
  'asset.protocol_type': { cs: 'Typ protokolu', en: 'Protocol Type' },
  'asset.net_throughput': { cs: 'Síťový průtok (Rx/Tx)', en: 'Network Throughput (Rx/Tx)' },
  'asset.disk_read': { cs: 'Čtení z disku', en: 'Disk Read' },
  'asset.disk_write': { cs: 'Zápis na disk', en: 'Disk Write' },
  'asset.inode_usage': { cs: 'Využití Inodů (fs)', en: 'Inode Usage (fs)' },
  'asset.swap_usage': { cs: 'Využití Swapu', en: 'Swap Usage' },
  'asset.tcp_retrans': { cs: 'TCP Retransmissions (/proc/net/snmp)', en: 'TCP Retransmissions (/proc/net/snmp)' },
  'asset.conntrack': { cs: 'Conntrack Spojení (Sockets)', en: 'Conntrack Connections (Sockets)' },
  'asset.moment_ago': { cs: 'Před chvílí', en: 'Just now' },
  'asset.ago_seconds': { cs: 'Před {s} s', en: '{s}s ago' },
  'asset.ago_minutes': { cs: 'Před {m} min', en: '{m}m ago' },
  'asset.ago_hours': { cs: 'Před {h}h {m}min', en: '{h}h {m}m ago' },
  'asset.range_24h': { cs: 'Posledních 24 hodin', en: 'Last 24 Hours' },
  'asset.range_7d': { cs: 'Posledních 7 dní', en: 'Last 7 Days' },
  'asset.range_30d': { cs: 'Posledních 30 dní', en: 'Last 30 Days' },
  'asset.time_range': { cs: 'Časový rozsah', en: 'Time Range' },

  // Websites & HTTP
  'websites.loading': { cs: 'Načítám seznam webů...', en: 'Loading website list...' },
  'websites.title': { cs: 'Sledované weby, cPanel & HTTP API', en: 'Monitored Websites, cPanel & HTTP API' },
  'websites.subtitle': { cs: 'Výhradně přehled dostupnosti webových stránek, cPanel statistik, SSL certifikátů a HTTP/HTTPS API.', en: 'A dedicated overview of website availability, cPanel stats, SSL certificates, and HTTP/HTTPS APIs.' },
  'websites.add_website': { cs: 'Přidat nový web', en: 'Add New Website' },
  'websites.add_website_modal_title': { cs: 'Přidat nový sledovaný web / HTTP API', en: 'Add New Monitored Website / HTTP API' },
  'websites.avg_latency': { cs: 'Průměrná latence HTTP', en: 'Average HTTP Latency' },
  'websites.ssl_valid': { cs: 'SSL Certifikáty', en: 'SSL Certificates' },
  'websites.monitored_count': { cs: 'Sledovaných webů', en: 'Monitored Sites' },
  'websites.load_error': { cs: 'Seznam webů se nepodařilo načíst.', en: 'Failed to load the website list.' },
  'websites.save_error': { cs: 'Web se nepodařilo uložit.', en: 'Failed to save the website.' },
  'websites.login_required_hint': { cs: 'Pro přidávání a úpravu monitorů se prosím přihlaste', en: 'Please log in to add and edit monitors' },
  'websites.current_uptime': { cs: 'Aktuální dostupnost webů', en: 'Current Website Uptime' },
  'websites.uptime_hint': { cs: '{up} z {total} dostupných právě teď', en: '{up} of {total} available right now' },
  'websites.check_interval': { cs: 'Interval kontrol podle nastavení monitoru', en: 'Check interval per monitor settings' },
  'websites.name_label': { cs: 'Název webu / služby', en: 'Website / Service Name' },
  'websites.name_placeholder': { cs: 'např. Moje Doména', en: 'e.g. My Domain' },
  'websites.url_label': { cs: 'URL Adresa (HTTP/HTTPS)', en: 'URL Address (HTTP/HTTPS)' },
  'websites.http_response': { cs: 'Odezva HTTP:', en: 'HTTP Response:' },
  'websites.http_status': { cs: 'Stav HTTP:', en: 'HTTP Status:' },
  'websites.cpanel_resources': { cs: 'cPanel Zdroje:', en: 'cPanel Resources:' },
  'websites.disk_label': { cs: 'Disk:', en: 'Disk:' },
  'websites.ram_label': { cs: 'RAM:', en: 'RAM:' },
  'websites.mysql_label': { cs: 'MySQL:', en: 'MySQL:' },
  'websites.bandwidth_label': { cs: 'Bandwidth:', en: 'Bandwidth:' },
  'websites.view_detail': { cs: 'Detail webu', en: 'View Website Detail' },

  // Incidents
  'incidents.loading': { cs: 'Načítám stav incidentů...', en: 'Loading incident status...' },
  'incidents.title': { cs: 'Správa Incidentů a Výpadků', en: 'Incidents & Outages Management' },
  'incidents.subtitle': { cs: 'Přehled výpadků cílových služeb, historie incidentů a stav měřících agentů.', en: 'Overview of target service outages, incident history, and probing agent status.' },
  'incidents.create': { cs: 'Nahlásit nový incident', en: 'Report New Incident' },
  'incidents.active_outages': { cs: 'Probíhající výpadky cílových služeb', en: 'Active Service Outages' },
  'incidents.all_ok': { cs: 'Všechny sledované cílové monitory a servery běží v pořádku bez výpadků.', en: 'All monitored target services and servers are operating normally without outages.' },
  'incidents.outage_start': { cs: 'Začátek výpadku', en: 'Outage Start' },
  'incidents.outage_end': { cs: 'Konec výpadku', en: 'Outage End' },
  'incidents.duration': { cs: 'Doba trvání', en: 'Duration' },
  'incidents.reason': { cs: 'Důvod / Příčina', en: 'Reason / Cause' },
  'incidents.probing_nodes': { cs: 'Stav měřících uzlů a agentů (Probing Infrastructure)', en: 'Probing Infrastructure & Agent Status' },
  'incidents.save_error': { cs: 'Incident se nepodařilo uložit.', en: 'Failed to save the incident.' },
  'incidents.login_required_hint': { cs: 'Pro zakládání incidentů se musíte přihlásit jako administrátor', en: 'You must log in as an administrator to create incidents' },
  'incidents.create_modal_title': { cs: 'Nahlásit nový incident / Plánovanou údržbu', en: 'Report New Incident / Scheduled Maintenance' },
  'incidents.name_label': { cs: 'Název incidentu', en: 'Incident Name' },
  'incidents.name_placeholder': { cs: 'např. Neplánovaná údržba databáze', en: 'e.g. Unplanned database maintenance' },
  'incidents.scope_label': { cs: 'Zasažená služba / Rozsah', en: 'Affected Service / Scope' },
  'incidents.scope_all_option': { cs: 'Všechny služby (Globální výpadek)', en: 'All services (Global outage)' },
  'incidents.detail_label': { cs: 'Detailní popis', en: 'Detailed Description' },
  'incidents.detail_placeholder': { cs: 'Popis problému, předpokládaná doba vyřešení...', en: 'Description of the problem, expected time to resolution...' },
  'incidents.active_badge': { cs: 'Aktivní výpadek', en: 'Active Outage' },
  'incidents.view_outage': { cs: 'Detail výpadku', en: 'View Outage Detail' },
  'incidents.manual_badge': { cs: 'Ručně nahlášeno', en: 'Manually Reported' },
  'incidents.created_label': { cs: 'Vytvořeno', en: 'Created' },
  'incidents.resolved_label': { cs: 'Vyřešeno', en: 'Resolved' },
  'incidents.probe_latency': { cs: 'Latence sondy', en: 'Probe Latency' },
  'incidents.probe_ok': { cs: 'Sonda OK', en: 'Probe OK' },
  'incidents.probe_offline': { cs: 'Sonda OFFLINE', en: 'Probe OFFLINE' },
  'incidents.selected_monitor': { cs: 'Vybraný monitor', en: 'Selected monitor' },
  'incidents.default_detail': { cs: 'Ručně nahlášený incident.', en: 'Manually reported incident.' },
  'incidents.scope_prefix': { cs: 'Rozsah', en: 'Scope' },

  // Insights
  'insights.loading': { cs: 'Analytický engine vyhodnocuje metriky infrastruktury...', en: 'Analytics engine is evaluating infrastructure metrics...' },
  'insights.title': { cs: 'AI & Inteligentní Analýza (Insights)', en: 'AI & Intelligent Analytics (Insights)' },
  'insights.subtitle': { cs: 'Predikce využití disků serverů, detekce anomálií a analytika HTTP služeb.', en: 'Disk usage prediction, anomaly detection, and HTTP service analytics.' },
  'insights.disk_pred': { cs: 'Predikce Disku (Servery & VPS)', en: 'Disk Usage Prediction (Servers & VPS)' },
  'insights.disk_pred_desc': { cs: 'Lineární regrese (7 dnů)', en: 'Linear Regression (7 Days)' },
  'insights.cpu_matrix': { cs: 'Hodinová Matice Špiček Vytížení (Hourly Peak Heatmap)', en: 'Hourly Peak Heatmap' },
  'insights.cpu_matrix_desc': { cs: 'Přehled hodin v týdnu s nejvyšší zátěží procesorů a síťového provozu', en: 'Weekly overview of peak CPU load and network throughput hours' },
  'insights.recommendations': { cs: 'Automatické analýzy a doporučení pro servery a infrastrukturu', en: 'Automated Analysis & Recommendations for Infrastructure' },
  'insights.disk_over_75': { cs: 'Využití hlavního diskového oddílu na serveru {name} přesáhlo hranici 75 %. Doporučujeme zkontrolovat zaplnění logů.', en: "The main disk partition usage on server {name} has exceeded the 75% threshold. We recommend checking log file sizes." },
  'insights.disk_healthy': { cs: 'Diskový prostor v pořádku', en: 'Disk space healthy' },
  'insights.disk_healthy_detail': { cs: 'Všechny serverové agenty mají dostatek volného diskového prostoru (nejvyšší využití disku je {hdd} % u {name}).', en: 'All server agents have sufficient free disk space (the highest disk usage is {hdd}% on {name}).' },
  'insights.disk_healthy_no_agents': { cs: 'Všechny sledované uzly mají diskový prostor v normě.', en: 'All monitored nodes have normal disk space levels.' },
  'insights.view_disk_detail': { cs: 'Detail disku', en: 'View Disk Detail' },
  'insights.cpu_card_title': { cs: 'Výkon Procesoru & RAM', en: 'CPU & RAM Performance' },
  'insights.cpu_card_subtitle': { cs: 'Stresové metriky agentů', en: 'Agent Stress Metrics' },
  'insights.cpu_stable': { cs: 'Spotřeba paměti a zátež procesoru u serveru {name} vykazuje stabilní hodnoty.', en: 'Memory consumption and CPU load on server {name} show stable values.' },
  'insights.cpu_all_optimal': { cs: 'Zatížení CPU/RAM u všech serverů je v optimálním rozmezí.', en: 'CPU/RAM load on all servers is within the optimal range.' },
  'insights.view_cpu_detail': { cs: 'Detail vytížení', en: 'View Load Detail' },
  'insights.web_card_title': { cs: 'Sledované Webové Služby', en: 'Monitored Web Services' },
  'insights.web_card_subtitle': { cs: 'SSL & Odezva HTTP', en: 'SSL & HTTP Latency' },
  'insights.ssl_valid_badge': { cs: 'SSL Platný', en: 'SSL Valid' },
  'insights.monitored_prefix': { cs: 'Sledováno {count} webových domén/API', en: 'Monitoring {count} web domains/APIs' },
  'insights.web_all_ok': { cs: 'Všechny webové stránky a HTTP endpointy odpovídají v pořádku.', en: 'All websites and HTTP endpoints are responding normally.' },
  'insights.go_to_websites': { cs: 'Přejít na Sledované weby', en: 'Go to Monitored Websites' },
  'insights.no_agents': { cs: 'Zatím nebyly připojeni žádní systémoví agenti. Pro diskovou analytiku nainstalujte agenta ze sekce API & Agenti.', en: 'No system agents are connected yet. Install an agent from the API & Agents section for disk analytics.' },
  'insights.rec_high_disk': { cs: 'Doporučujeme promazat staré logy v /var/log nebo rozšířit diskový oddíl (aktuálně zaplněno {hdd} %).', en: 'We recommend clearing old logs in /var/log or expanding the disk partition (currently {hdd}% full).' },
  'insights.rec_high_cpu': { cs: 'Zaznamenáno vyšší vytížení procesoru ({cpu} %). Zkontrolujte spuštěné procesy.', en: 'Higher CPU load detected ({cpu}%). Check running processes.' },
  'insights.rec_optimal': { cs: 'Provoz zařízení je v optimálním stavu. Odezva {ms} ms{extra}.', en: 'Device operation is optimal. Latency {ms} ms{extra}.' },
  'insights.open_link': { cs: 'Otevřít', en: 'Open' },

  // Reports & SLA
  'reports.loading': { cs: 'Načítám SLA metriky z databáze…', en: 'Loading SLA metrics from database…' },
  'reports.title': { cs: 'SLA Výkazy & Statistika Dle Serverů', en: 'SLA Reports & Per-Server Statistics' },
  'reports.subtitle': { cs: 'Reálná data z monitorovací databáze — uptime, výpadky, doba obnovení (MTTR) a důvody výpadků.', en: 'Real data from the monitoring database — uptime, outages, recovery time (MTTR), and outage causes.' },
  'reports.export_pdf': { cs: 'Tisknout / PDF', en: 'Print / PDF' },
  'reports.period': { cs: 'Období reportu', en: 'Report Period' },
  'reports.period_30d': { cs: 'Posledních 30 dní', en: 'Last 30 Days' },
  'reports.period_90d': { cs: 'Posledních 90 dní', en: 'Last 90 Days' },
  'reports.target_sla': { cs: 'Cílové SLA', en: 'SLA Target' },
  'reports.actual_sla': { cs: 'Reálné SLA', en: 'Actual SLA' },
  'reports.mttr': { cs: 'Průměrná doba obnovení (MTTR)', en: 'Mean Time To Recovery (MTTR)' },
  'reports.outage_time': { cs: 'Celkový čas výpadku', en: 'Total Outage Time' },
  'reports.no_api_data': { cs: 'Žádná data z API. Zkontrolujte, že cron.php běží a monitor_logs obsahuje záznamy.', en: 'No data from the API. Check that cron.php is running and monitor_logs contains records.' },
  'reports.load_error': { cs: 'Nepodařilo se načíst SLA data.', en: 'Failed to load SLA data.' },
  'reports.csv_uptime': { cs: 'Uptime SLA (%)', en: 'Uptime SLA (%)' },
  'reports.csv_outage_min': { cs: 'Celkový výpadek (min)', en: 'Total Outage (min)' },
  'reports.csv_total_checks': { cs: 'Celkem kontrol', en: 'Total Checks' },
  'reports.csv_mttr': { cs: 'MTTR (s)', en: 'MTTR (s)' },
  'reports.export_csv': { cs: 'Exportovat CSV', en: 'Export CSV' },
  'reports.overall_sla': { cs: 'Celkové plnění SLA', en: 'Overall SLA Compliance' },
  'reports.sla_target_value': { cs: 'SLA Cíl: {goal} %', en: 'SLA Target: {goal}%' },
  'reports.monitored_count': { cs: 'Sledované servery/weby', en: 'Monitored Servers/Websites' },
  'reports.total_count': { cs: '{count} celkem', en: '{count} total' },
  'reports.sla_compliant_count': { cs: '{ok} / {total} splňuje SLA', en: '{ok} / {total} meeting SLA' },
  'reports.total_outage_30d': { cs: 'Celkový výpadek (30 d)', en: 'Total Outage (30d)' },
  'reports.outage_sum_hint': { cs: 'Suma výpadků všech cílů', en: 'Sum of outages across all targets' },
  'reports.mttr_hint': { cs: 'Automatické obnovení (down→up)', en: 'Automatic recovery (down→up)' },
  'reports.sla_per_monitor_title': { cs: 'Plnění SLA garancí po jednotlivých serverech a webech', en: 'SLA Compliance by Individual Server and Website' },
  'reports.sla_per_monitor_desc': { cs: 'Reálná dostupnost z databáze za posledních 30 dní. Klikněte na řádek pro detail výpadku.', en: 'Real availability from the database over the last 30 days. Click a row for outage detail.' },
  'reports.no_monitors': { cs: 'Žádné monitory k zobrazení.', en: 'No monitors to display.' },
  'reports.outage_minutes_inline': { cs: 'Výpadek: {min} min', en: 'Outage: {min} min' },
  'reports.total_checks_30d': { cs: 'Celkem kontrol (30d)', en: 'Total Checks (30d)' },
  'reports.mttr_label': { cs: 'MTTR (doba obnovení)', en: 'MTTR (recovery time)' },
  'reports.no_outage': { cs: 'Bez výpadku', en: 'No outage' },
  'reports.current_status': { cs: 'Aktuální stav', en: 'Current Status' },
  'reports.percentile_title': { cs: 'Percentilové Rozložení Latence (p50 / p95 / p99)', en: 'Latency Percentile Distribution (p50 / p95 / p99)' },
  'reports.percentile_aria': { cs: 'Co znamenají percentily odezvy', en: 'What the latency percentiles mean' },
  'reports.percentile_tooltip_title': { cs: 'Co percentily znamenají', en: 'What the percentiles mean' },
  'reports.p50_label': { cs: 'p50 (medián):', en: 'p50 (median):' },
  'reports.p50_desc': { cs: 'polovina kontrol byla rychlejší, polovina pomalejší — nejlépe vystihuje typickou odezvu.', en: 'half of the checks were faster, half slower — best represents typical latency.' },
  'reports.p95_label': { cs: 'p95:', en: 'p95:' },
  'reports.p95_desc': { cs: '95 % kontrol bylo rychlejších; zbylých 5 % jsou špičky (dočasné zpomalení, zátěž).', en: '95% of checks were faster; the remaining 5% are spikes (temporary slowdowns, load).' },
  'reports.p99_label': { cs: 'p99:', en: 'p99:' },
  'reports.p99_desc': { cs: 'jen 1 % kontrol bylo pomalejších — ojedinělé extrémní špičky, často síťový problém nebo přetížený server.', en: 'only 1% of checks were slower — rare extreme spikes, often a network issue or overloaded server.' },
  'reports.percentile_hint': { cs: 'Vysoké p95/p99 při nízkém p50 = nekonzistentní výkon. Hledejte příčinu v době těch špiček (log serveru, zátěž), ne v průměru.', en: 'High p95/p99 with a low p50 means inconsistent performance. Look for the cause at the time of those spikes (server logs, load), not in the average.' },
  'reports.p50_value_label': { cs: 'p50 (Medián):', en: 'p50 (Median):' },
  'reports.p95_value_label': { cs: 'p95 (Špičky):', en: 'p95 (Spikes):' },
  'reports.p99_value_label': { cs: 'p99 (Kritické špičky):', en: 'p99 (Critical Spikes):' },
  'reports.last_outage_title': { cs: 'Poslední výpadek', en: 'Last Outage' },
  'reports.outage_field_start': { cs: 'Začátek:', en: 'Start:' },
  'reports.outage_field_end': { cs: 'Konec:', en: 'End:' },
  'reports.outage_field_duration': { cs: 'Trvání:', en: 'Duration:' },
  'reports.outage_field_status': { cs: 'Stav:', en: 'Status:' },
  'reports.outage_ongoing': { cs: 'Stále probíhá ⚠️', en: 'Still ongoing ⚠️' },
  'reports.resolved_badge': { cs: 'Vyřešeno', en: 'Resolved' },
  'reports.ongoing_badge': { cs: 'Probíhá', en: 'Ongoing' },
  'reports.reason_label': { cs: 'Důvod:', en: 'Reason:' },
  'reports.no_outage_30d': { cs: 'Žádný výpadek za posledních 30 dní.', en: 'No outages in the last 30 days.' },
  'reports.view_detail': { cs: 'Otevřít detail', en: 'View Detail' },
  'reports.csv_export_title': { cs: 'Měsíční SLA Výkaz (CSV Export)', en: 'Monthly SLA Report (CSV Export)' },
  'reports.csv_export_desc': { cs: 'Stáhněte si kompletní CSV soubor s detailním výpočtem Uptime %, počty výpadků a latencí.', en: 'Download a complete CSV file with detailed Uptime % calculations, outage counts, and latency.' },
  'reports.csv_export_btn': { cs: 'Stáhnout CSV report', en: 'Download CSV Report' },
  'reports.prometheus_title': { cs: 'Prometheus Exportér Metrik', en: 'Prometheus Metrics Exporter' },
  'reports.prometheus_desc': { cs: 'Integrační rozhraní pro napojení externích systémů, Grafany nebo Prometheus serveru.', en: 'Integration interface for connecting external systems, Grafana, or a Prometheus server.' },
  'reports.prometheus_btn': { cs: 'Otevřít Prometheus výstup', en: 'Open Prometheus Output' },
  'reports.prometheus_active': { cs: 'Aktivní', en: 'Active' },
  'reports.prometheus_desc_active': { cs: 'Integrační rozhraní pro napojení externích systémů, Grafany nebo Prometheus serveru s vaším přístupovým tokenem.', en: 'Integration interface for connecting external systems, Grafana, or a Prometheus server with your access token.' },
  'reports.copy_url': { cs: 'Kopírovat URL metrik', en: 'Copy Metrics URL' },
  'common.copied': { cs: 'Zkopírováno!', en: 'Copied!' },
  'reports.prometheus_inactive': { cs: 'Vyžaduje token', en: 'Requires Token' },
  'reports.prometheus_inactive_desc': { cs: 'Metriky jsou chráněny proti neautorizovanému přístupu. Vygenerujte přístupový token pro aktivaci endpointu.', en: 'Metrics are protected against unauthorized access. Generate an access token to activate the endpoint.' },
  'reports.generate_token_btn': { cs: 'Aktivovat Prometheus token (1-klik)', en: 'Activate Prometheus Token (1-Click)' },
  'reports.manage_in_settings': { cs: 'Spravovat v Nastavení', en: 'Manage in Settings' },
  'reports.pdf_header_subtitle': { cs: 'Oficiální Garance Uptime, Výpadky & SLA Auditní Výkaz', en: 'Official Uptime Guarantee, Outages & SLA Audit Report' },
  'reports.pdf_audit_report': { cs: 'SLA Audit Report', en: 'SLA Audit Report' },
  'reports.pdf_generated_at': { cs: 'Vygenerováno: {date}', en: 'Generated: {date}' },
  'reports.pdf_source': { cs: 'Zdroj: bloodkings.eu / status API', en: 'Source: bloodkings.eu / status API' },

  // Users
  'users.title': { cs: 'Správa Uživatelů a Oprávnění', en: 'User & Permission Management' },
  'users.subtitle': { cs: 'Správa uživatelských účtů, rolí (Admin / Member / Viewer) a dvoufázového ověření (2FA).', en: 'Manage user accounts, roles (Admin / Member / Viewer), and 2FA authentication.' },
  'users.add_user': { cs: 'Přidat uživatele', en: 'Add User' },

  // API & Agents
  'api_agents.title': { cs: 'API Klíče, Bezpečnost & Správa Agentů', en: 'API Keys, Security & Agent Management' },
  'api_agents.subtitle': { cs: 'Verze agentů, kontrola bezpečnostních aktualizací, HMAC klíče a instalace.', en: 'Agent versions, security update checks, HMAC keys, and installation.' },
  'api_agents.install_cmd': { cs: 'Jednorázový instalační příkaz agenta (Linux / Debian / Ubuntu / OpenWrt)', en: 'One-line Agent Installation Command (Linux / Debian / Ubuntu / OpenWrt)' },
  'api_agents.copy_cmd': { cs: 'Kopírovat příkaz', en: 'Copy Command' },
  'api_agents.installed_agents': { cs: 'Stav verzí a aktualizací spuštěných agentů', en: 'Installed Agents Version & Status' },
  'api_agents.agent_os': { cs: 'Operační systém', en: 'Operating System' },
  'api_agents.agent_version': { cs: 'Verze agenta', en: 'Agent Version' },
  'api_agents.login_required_title': { cs: 'Přihlášení vyžadováno', en: 'Login Required' },
  'api_agents.desc_linux': { cs: 'Automatický sběr CPU, RAM, zátěže disku, běžících procesů a služeb pro Debian, Ubuntu, CentOS a RHEL.', en: 'Automatic collection of CPU, RAM, disk load, running processes, and services for Debian, Ubuntu, CentOS, and RHEL.' },
  'api_agents.note_linux': { cs: 'Skript automaticky nainstaluje systémovou službu systemd (bk-agent.service) a spustí pozadí polling.', en: 'The script automatically installs a systemd service (bk-agent.service) and starts background polling.' },
  'api_agents.desc_openwrt': { cs: 'Lehký shell agent přímo pro routery OpenWrt/LEDE. Využívá ubus, iwinfo, /proc a podporuje bezpečné Remote Actions (potvrzovací pingy).', en: 'A lightweight shell agent built for OpenWrt/LEDE routers. Uses ubus, iwinfo, /proc, and supports secure Remote Actions (confirmation pings).' },
  'api_agents.note_openwrt': { cs: 'Do /etc/crontabs/root přidejte řádek: * * * * * /usr/bin/agent_openwrt.sh >/dev/null 2>&1', en: 'Add this line to /etc/crontabs/root: * * * * * /usr/bin/agent_openwrt.sh >/dev/null 2>&1' },
  'api_agents.desc_windows': { cs: 'PowerShell agent pro Windows Server 2016 / 2019 / 2022 s automatickou registrací do Windows Task Scheduler.', en: 'A PowerShell agent for Windows Server 2016 / 2019 / 2022 with automatic registration in Windows Task Scheduler.' },
  'api_agents.note_windows': { cs: 'Spusťte v PowerShell okénku správce (Run as Administrator).', en: 'Run it in an administrator PowerShell window (Run as Administrator).' },
  'api_agents.desc_cpanel': { cs: 'Stáhněte cpanel_stats.php do kořenového adresáře hostingu pro veřejný sběr diskového prostoru, RAM a MySQL zátěže.', en: 'Download cpanel_stats.php into the hosting root directory to publicly collect disk space, RAM, and MySQL load.' },
  'api_agents.note_cpanel': { cs: 'URL k souboru s vaším tajným klíčem následně zadejte v detailu monitoru v záložce Nastavení Webu.', en: "Then enter the file's URL with your secret key in the monitor detail's Website Settings tab." },
  'api_agents.desc_docker': { cs: 'Izolovaný Docker kontejner pro provoz v prostředí Docker / Kubernetes bez zásahu do hostitelského OS.', en: 'An isolated Docker container for running in Docker / Kubernetes environments without touching the host OS.' },
  'api_agents.note_docker': { cs: 'Kontejner mapuje pouze /proc v režimu jen pro čtení (read-only) pro nulové bezpečnostní riziko.', en: 'The container mounts only /proc in read-only mode for zero security risk.' },
  'api_agents.install_scripts_title': { cs: 'Instalační skripty agentů dle platformy', en: 'Agent Installation Scripts by Platform' },
  'api_agents.install_scripts_desc': { cs: 'Vyberte váš cílový systém pro zobrazení správného příkazu a postupu instalace', en: 'Select your target system to see the correct command and installation steps' },
  'api_agents.setup_note_label': { cs: 'Poznámka k nastavení:', en: 'Setup note:' },
  'api_agents.version_status_title': { cs: 'Stav verzí & Automatické aktualizace agentů ({count})', en: 'Version Status & Automatic Agent Updates ({count})' },
  'api_agents.recommended_version': { cs: 'Aktuální doporučená verze systému:', en: 'Current recommended system version:' },
  'api_agents.status_outdated': { cs: '🔴 Zjištěna neaktuální verze agenta!', en: '🔴 Outdated agent version detected!' },
  'api_agents.status_auto_update_off': { cs: '⚠️ U některých agentů vypnuty auto-updates', en: '⚠️ Auto-updates disabled on some agents' },
  'api_agents.status_all_ok': { cs: 'Všichni agenti aktuální & auto-updates OK ✅', en: 'All agents up to date & auto-updates OK ✅' },
  'api_agents.email_alerts_on': { cs: 'E-mail výstrahy zapnuty 📧', en: 'Email alerts on 📧' },
  'api_agents.email_alerts_off': { cs: 'E-mail výstrahy vypnuty 🔕', en: 'Email alerts off 🔕' },
  'api_agents.loading': { cs: 'Načítám agenty…', en: 'Loading agents…' },
  'api_agents.no_agents': { cs: 'Žádní registrovaní agenti v databázi.', en: 'No registered agents in the database.' },
  'api_agents.inactive': { cs: 'Neaktivní', en: 'Inactive' },
  'api_agents.version_outdated': { cs: '🔴 v{version} (Neaktuální — Doporučeno v{latest})', en: '🔴 v{version} (Outdated — Recommended v{latest})' },
  'api_agents.version_current': { cs: '🟢 v{version} (Aktuální verze)', en: '🟢 v{version} (Current Version)' },
  'api_agents.version_unreported': { cs: 'Verze nehlášena', en: 'Version not reported' },
  'api_agents.auto_update_on': { cs: 'Auto-updates: Zapnuto', en: 'Auto-updates: On' },
  'api_agents.auto_update_off': { cs: 'Auto-updates: VYPNUTO', en: 'Auto-updates: OFF' },
  'api_agents.outdated_warning_title': { cs: 'Agent je neaktuální!', en: 'The agent is outdated!' },
  'api_agents.outdated_warning_desc': { cs: 'Používá verzi v{version}, doporučená verze je v{latest}. Při neaktuální verzi systém zařazuje varovný incident a zasílá notifikaci administrátorům.', en: 'It is running version v{version}; the recommended version is v{latest}. When outdated, the system logs a warning incident and notifies administrators.' },
  'api_agents.auto_update_disabled_title': { cs: 'Automatické aktualizace jsou vypnuty:', en: 'Automatic updates are disabled:' },
  'api_agents.auto_update_disabled_desc': { cs: 'Doporučujeme v konfiguraci agenta (`agent.cfg` nebo `agent_openwrt.cfg`) nastavit', en: 'We recommend setting, in the agent configuration (`agent.cfg` or `agent_openwrt.cfg`),' },
  'api_agents.auto_update_disabled_desc_suffix': { cs: ', aby se bezpečnostní záplaty a opravy instalovaly automaticky bez nutnosti ručního zásahu.', en: ' so security patches and fixes are installed automatically without manual intervention.' },
  'api_agents.privacy_title': { cs: 'Záruka Soukromí & Zero Telemetry', en: 'Privacy Guarantee & Zero Telemetry' },
  'api_agents.privacy_desc': { cs: '0 % naměřených dat neopouští vaše servery ani není odesíláno třetím stranám. Všechny metriky se ukládají lokálně ve vaší MySQL/PostgreSQL databázi pod vaší plnou kontrolou.', en: '0% of measured data ever leaves your servers or is sent to third parties. All metrics are stored locally in your own MySQL/PostgreSQL database, fully under your control.' },
  'api_agents.auth_title': { cs: 'Autentizace agentů & Notifikace verze', en: 'Agent Authentication & Version Notifications' },
  'api_agents.auth_desc': { cs: 'Při detekci zastaralé verze agenta nebo selhání Remote Action systém vygeneruje varovný incident v sekci Incidenty a odešle e-mailovou/SMS výstrahu administrátorům.', en: 'When an outdated agent version or a failed Remote Action is detected, the system logs a warning incident in the Incidents section and sends an email/SMS alert to administrators.' },
  'api_agents.key_hmac_badge': { cs: 'Klíč + HMAC-SHA256', en: 'Key + HMAC-SHA256' },

  // Setup / Login
  'setup.verifying': { cs: 'Ověřuji údaje...', en: 'Verifying credentials...' },
  'setup.confirm_2fa': { cs: 'Potvrdit 2FA kód a přihlásit se', en: 'Confirm 2FA Code & Log In' },
  'setup.finish_install': { cs: 'Dokončit instalaci a přihlásit se', en: 'Finish Installation & Log In' },

  // Settings
  'settings.title': { cs: 'Nastavení Systému & Notifikací', en: 'System & Notification Settings' },
  'settings.subtitle': { cs: 'Správa parametrů platformy, notifikačních kanálů, OAuth integrací a brandingu.', en: 'Manage platform parameters, notification channels, OAuth integrations, and branding.' },
  'settings.save_success': { cs: 'Nastavení bylo úspěšně uloženo.', en: 'Settings saved successfully.' },
  'settings.notifications': { cs: 'Notifikace & Upozornění', en: 'Notifications & Alerts' },
  'settings.load_error': { cs: 'Nepodařilo se načíst nastavení z API.', en: 'Failed to load settings from the API.' },
  'settings.save_error': { cs: 'Chyba při ukládání.', en: 'Error while saving.' },
  'settings.digest_unknown_result': { cs: 'Neznámý výsledek.', en: 'Unknown result.' },
  'settings.digest_comm_error': { cs: 'Chyba při komunikaci se serverem.', en: 'Error communicating with the server.' },
  'settings.login_required_title': { cs: 'Přihlášení vyžadováno', en: 'Login Required' },
  'settings.login_required_desc': { cs: 'Konfigurace nastavení je přístupná pouze přihlášeným administrátorům.', en: 'Settings configuration is only accessible to logged-in administrators.' },
  'settings.go_to_login': { cs: 'Přejít na přihlášení', en: 'Go to Login' },
  'settings.insufficient_perms_title': { cs: 'Nedostatečná oprávnění', en: 'Insufficient Permissions' },
  'settings.insufficient_perms_desc_prefix': { cs: 'Konfigurace systémových nastavení je přístupná výhradně uživatelům s rolí', en: 'System settings configuration is only accessible to users with the role' },
  'settings.role_admin': { cs: 'administrátor', en: 'administrator' },
  'settings.loading': { cs: 'Načítání nastavení…', en: 'Loading settings…' },
  'settings.tab_general': { cs: 'Obecné', en: 'General' },
  'settings.tab_notifications': { cs: 'Notifikace', en: 'Notifications' },
  'settings.tab_integrations': { cs: 'Integrace', en: 'Integrations' },
  'settings.tab_appearance': { cs: 'Vzhled', en: 'Appearance' },
  'settings.test_sent': { cs: 'Testovací notifikace odeslána na kanál: {channel}', en: 'Test notification sent to channel: {channel}' },
  'settings.test_ok': { cs: 'Test OK', en: 'Test OK' },
  'settings.general_section': { cs: 'Obecné nastavení', en: 'General Settings' },
  'settings.site_title_label': { cs: 'Název status stránky', en: 'Status Page Title' },
  'settings.site_url_label': { cs: 'Veřejná URL status stránky (bez lomítka na konci)', en: 'Public Status Page URL (no trailing slash)' },
  'settings.site_url_hint': { cs: 'Používá se k prokliku z e-mailů zpět na konkrétní monitor.', en: 'Used for click-through links from emails back to a specific monitor.' },
  'settings.cron_key_label': { cs: 'Cron Bezpečnostní Klíč (URL parametr ?key=...)', en: 'Cron Security Key (URL parameter ?key=...)' },
  'settings.cron_key_placeholder': { cs: 'Např. secure123key', en: 'e.g. secure123key' },
  'settings.cron_url_label': { cs: 'Cron URL:', en: 'Cron URL:' },
  'settings.cron_location_label': { cs: 'Lokace hlavního serveru', en: 'Main Server Location' },
  'settings.cron_location_placeholder': { cs: 'Necháte prázdné pro AUTO detekci nebo např. 🇩🇪 Frankfurt, DE', en: 'Leave empty for AUTO detection, or e.g. 🇩🇪 Frankfurt, DE' },
  'settings.cron_location_hint': { cs: 'Prázdné nebo AUTO = automaticky zjištěno dle IP hostingu.', en: 'Empty or AUTO = automatically detected from the hosting IP.' },
  'settings.sla_goal_label': { cs: 'Cílová dostupnost SLA (%)', en: 'SLA Uptime Target (%)' },
  'settings.sla_goal_hint': { cs: 'Používá se v měsíčním infrastructure reportu.', en: 'Used in the monthly infrastructure report.' },
  'settings.ssl_alert_label': { cs: 'Varování před vypršením SSL (dní)', en: 'SSL Expiry Warning (days)' },
  'settings.smtp_title': { cs: 'E-mailové Notifikace (SMTP)', en: 'Email Notifications (SMTP)' },
  'settings.smtp_desc': { cs: 'SMTP připojení pro odesílání notifikací. Prázdný SMTP server = výchozí PHP mail().', en: 'SMTP connection for sending notifications. Empty SMTP server = default PHP mail().' },
  'settings.smtp_locked': { cs: 'SMTP je nastaveno pevně v', en: 'SMTP is hardcoded in' },
  'settings.smtp_locked_suffix': { cs: 'a nelze ho změnit odsud.', en: 'and cannot be changed from here.' },
  'settings.email_lang_label': { cs: 'Jazyk odchozích e-mailů', en: 'Outgoing Email Language' },
  'settings.lang_cs': { cs: 'Čeština', en: 'Czech' },
  'settings.smtp_user_label': { cs: 'Odesílatel zpráv (From E-mail)', en: 'Sender Address (From Email)' },
  'settings.smtp_host_label': { cs: 'SMTP Server (Host)', en: 'SMTP Server (Host)' },
  'settings.smtp_secure_label': { cs: 'SMTP Zabezpečení', en: 'SMTP Security' },
  'settings.smtp_secure_none': { cs: 'Bez zabezpečení', en: 'No encryption' },
  'settings.smtp_pass_label': { cs: 'SMTP Heslo', en: 'SMTP Password' },
  'settings.smtp_pass_placeholder': { cs: 'Heslo k e-mailové schránce', en: 'Password for the mailbox' },
  'settings.channel_email': { cs: 'E-mail (SMTP)', en: 'Email (SMTP)' },
  'settings.send_test_email': { cs: 'Odeslat testovací e-mail', en: 'Send Test Email' },
  'settings.sms_title': { cs: 'SMS Gateway Notifikace', en: 'SMS Gateway Notifications' },
  'settings.sms_gateway_label': { cs: 'Placená SMS brána', en: 'Paid SMS Gateway' },
  'settings.sms_gateway_none': { cs: 'Žádná (SMS notifikace vypnuty)', en: 'None (SMS notifications disabled)' },
  'settings.twilio_from_label': { cs: 'Twilio Odesílací číslo (From)', en: 'Twilio Sending Number (From)' },
  'settings.smsbrana_user_label': { cs: 'SMS Brána - Přihlašovací jméno (API)', en: 'SMS Gateway - Login Name (API)' },
  'settings.smsbrana_pass_label': { cs: 'SMS Brána - Heslo (API)', en: 'SMS Gateway - Password (API)' },
  'settings.vps_agent_title': { cs: 'VPS Agent Nastavení', en: 'VPS Agent Settings' },
  'settings.agent_offline_timeout_label': { cs: 'Časový limit pro označení agenta za offline (minuty)', en: 'Timeout to Mark Agent Offline (minutes)' },
  'settings.agent_offline_timeout_hint': { cs: 'Doba neaktivity, po které bude agent považován za odpojeného. 0 = detekce neaktivity vypnuta.', en: 'Period of inactivity after which the agent is considered disconnected. 0 = inactivity detection disabled.' },
  'settings.agent_outdated_email_label': { cs: 'Zasílat e-mailová varování při detekci neaktuální verze agenta (Outdated Agent Alert)', en: 'Send email warnings when an outdated agent version is detected (Outdated Agent Alert)' },
  'settings.agent_resource_alert_label': { cs: 'Upozorňovat na překročení limitů CPU/RAM/HDD', en: 'Alert on CPU/RAM/HDD limit breaches' },
  'settings.agent_admin_only_label': { cs: 'Upozornění VPS agenta doručovat pouze administrátorům', en: 'Deliver VPS agent alerts to administrators only' },
  'settings.agent_outdated_hint': { cs: 'Při zjištění zastaralé verze agenta systém odesílá e-mailovou výstrahu a eviduje varovný incident.', en: 'When an outdated agent version is detected, the system sends an email alert and logs a warning incident.' },
  'settings.agent_token_label': { cs: 'Token pro auto-registraci agentů', en: 'Agent Auto-Registration Token' },
  'settings.webhooks_title': { cs: 'Webhooky & Externí Notifikace', en: 'Webhooks & External Notifications' },
  'settings.test_discord': { cs: 'Test Discord', en: 'Test Discord' },
  'settings.test_telegram': { cs: 'Test Telegram', en: 'Test Telegram' },
  'settings.whatsapp_desc': { cs: 'Konfigurace WhatsApp API pro doručování výstrah (Twilio WhatsApp, UltraMsg nebo Meta Cloud API).', en: 'Configure the WhatsApp API for delivering alerts (Twilio WhatsApp, UltraMsg, or Meta Cloud API).' },
  'settings.whatsapp_token_label': { cs: 'WhatsApp Access Token / Token', en: 'WhatsApp Access Token' },
  'settings.whatsapp_phone_label': { cs: 'Cílové / Odesílací číslo WhatsApp', en: 'Target / Sending WhatsApp Number' },
  'settings.test_whatsapp': { cs: 'Test WhatsApp Gateway', en: 'Test WhatsApp Gateway' },
  'settings.digest_title': { cs: 'Týdenní & Měsíční Digest Report', en: 'Weekly & Monthly Digest Report' },
  'settings.digest_desc': { cs: 'Digest se odesílá automaticky cronem (vždy v pondělí / 1. den v měsíci). Zde můžete odeslat ruční e-mailový digest všem administrátorům.', en: 'The digest is sent automatically by cron (every Monday / 1st of the month). Here you can manually send an email digest to all administrators.' },
  'settings.weekly_digest_title': { cs: 'Týdenní Souhrn (Weekly Digest)', en: 'Weekly Summary (Weekly Digest)' },
  'settings.weekly_digest_desc': { cs: 'Souhrnný e-mail se statistikami SLA, incidenty a průměrnou latencí za posledních 7 dnů.', en: 'A summary email with SLA statistics, incidents, and average latency over the last 7 days.' },
  'settings.sending': { cs: 'Odesílám…', en: 'Sending…' },
  'settings.send_weekly_digest': { cs: 'Odeslat Týdenní Digest', en: 'Send Weekly Digest' },
  'settings.preview': { cs: 'Náhled', en: 'Preview' },
  'settings.monthly_digest_title': { cs: 'Měsíční Souhrn (Monthly Digest)', en: 'Monthly Summary (Monthly Digest)' },
  'settings.monthly_digest_desc': { cs: 'Kompletní měsíční auditní zpráva pro vedení se všemi výpadky, MTTR a plněním SLA.', en: 'A complete monthly audit report for management covering all outages, MTTR, and SLA compliance.' },
  'settings.send_monthly_digest': { cs: 'Odeslat Měsíční Digest', en: 'Send Monthly Digest' },
  'settings.subs_title': { cs: 'Odběr notifikací pro můj účet', en: 'Notification Subscriptions for My Account' },
  'settings.subs_desc': { cs: 'Zvolte, pro které monitory chcete dostávat e-mailové, SMS nebo WhatsApp notifikace při výpadku.', en: 'Choose which monitors you want to receive email, SMS, or WhatsApp notifications for on outage.' },
  'settings.subs_loading': { cs: 'Načítám odběry…', en: 'Loading subscriptions…' },
  'settings.subs_none': { cs: 'Žádné monitory k odběru.', en: 'No monitors to subscribe to.' },
  'settings.subs_col_monitor': { cs: 'Monitor', en: 'Monitor' },
  'settings.subs_saved': { cs: 'Uloženo!', en: 'Saved!' },
  'settings.subs_save': { cs: 'Uložit odběry', en: 'Save Subscriptions' },
  'settings.metrics_token_label': { cs: 'Přístupový token pro /status/metrics.php', en: 'Access Token for /status/metrics.php' },
  'settings.metrics_token_placeholder': { cs: 'Prázdné = endpoint vypnutý', en: 'Empty = endpoint disabled' },
  'settings.metrics_token_hint': { cs: 'Scraper předává token jako ?token=... nebo hlavičkou Authorization: Bearer. Vygenerujte např. openssl rand -hex 24.', en: 'The scraper passes the token as ?token=... or via the Authorization: Bearer header. Generate one with e.g. openssl rand -hex 24.' },
  'settings.oauth_title': { cs: 'Přihlášení přes OAuth (SSO)', en: 'OAuth Login (SSO)' },
  'settings.oauth_desc_prefix': { cs: 'OAuth přihlášení funguje jen pro účty, které si ho samy propojily v Profilu. Jako Authorization/Redirect callback URL u každého poskytovatele zadejte URL vaší', en: 'OAuth login only works for accounts that have linked it themselves in their Profile. As the Authorization/Redirect callback URL for each provider, enter the URL of your' },
  'settings.branding_title': { cs: 'Vlastní branding (Custom Branding)', en: 'Custom Branding' },
  'settings.logo_url_label': { cs: 'Adresa loga (Logo URL)', en: 'Logo Address (Logo URL)' },
  'settings.accent_color_label': { cs: 'Akcentová barva (Hex Color)', en: 'Accent Color (Hex Color)' },
  'settings.nav_links_label': { cs: 'Vlastní odkazy v menu (JSON formát)', en: 'Custom Menu Links (JSON format)' },
  'settings.nav_links_hint': { cs: 'Zadejte pole objektů: [{"name": "Nápověda", "url": "..."}]', en: 'Enter an array of objects: [{"name": "Help", "url": "..."}]' },
  'settings.portal_url_label': { cs: 'Odkaz na nadřazený portál (nepovinné)', en: 'Parent Portal Link (optional)' },
  'settings.portal_url_hint': { cs: "Zobrazí se v menu jako 'Portál'. Prázdné = odkaz se nezobrazí.", en: "Displayed in the menu as 'Portal'. Empty = link is not shown." },
  'settings.saving': { cs: 'Ukládání…', en: 'Saving…' },
  'settings.saved': { cs: 'Uloženo!', en: 'Saved!' },
  'settings.save_all': { cs: 'Uložit všechna nastavení', en: 'Save All Settings' },
  'settings.env_locked_title': { cs: 'Definováno v config.php / prostředí', en: 'Defined in config.php / environment' },

  // Keys that were wrapped in t() with a Czech string as the "fallback" -
  // that fallback only applies in English mode, so it needs to actually be
  // English. Filled in properly here instead of leaving the key undefined.
  'api_agents.login_required_desc': { cs: 'Správa API klíčů a instalačních skriptů je přístupná pouze přihlášeným administrátorům.', en: 'Managing API keys and installation scripts is only accessible to logged-in administrators.' },
  'dashboard.col_monitor': { cs: 'Zobrazit', en: 'Show' },
  'dashboard.showing': { cs: 'Zobrazeno {shown} z {total} monitorovaných služeb', en: 'Showing {shown} of {total} monitored services' },
  'events.showing': { cs: 'Zobrazeno {shown} z {total} událostí', en: 'Showing {shown} of {total} events' },
  'incidents.all_scope': { cs: 'Všechny služby (Globální incident)', en: 'All services (Global incident)' },
  'incidents.probes_ok': { cs: 'Všechny testovací sondy pracují bez výpadků.', en: 'All probing nodes are operating normally.' },
  'incidents.probing_hint': { cs: 'Tyto uzly pouze provádějí měření z různých geografických lokací a NEJSOU cílovými službami.', en: 'These nodes only perform measurements from various geographic locations and are NOT target services.' },
  'incidents.public_notice': { cs: 'Prohlížení incidentů je veřejné. Pro ruční zakládání a úpravu incidentů se přihlaste.', en: 'Browsing incidents is public. Log in to manually create or edit incidents.' },
  'status_pages.desc': { cs: 'Zobrazuje stav sledovaných služeb v reálném čase a příchozí plánované údržby.', en: 'Displays the real-time status of monitored services and upcoming scheduled maintenance.' },
  'status_pages.subtitle': { cs: 'Zobrazuje veřejnou status stránku dostupnosti všech sledovaných služeb a plánovaných údržeb v reálném čase.', en: 'Shows the public status page for the availability of all monitored services and scheduled maintenance in real time.' },
  'websites.public_notice': { cs: 'Přehled stavu webů a cPanelu je veřejně přístupný. Pro přidávání nových domén se prosím přihlaste.', en: 'The website and cPanel status overview is publicly visible. Please log in to add new domains.' },
  'websites.responding_count': { cs: 'Z {count} odpovídajících webů', en: 'From {count} responding websites' },
  'websites.ssl_hint': { cs: 'Všechny certifikáty platné', en: 'All certificates valid' },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'cs',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('bk_lang');
    return saved === 'en' ? 'en' : 'cs';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('bk_lang', newLang);
  };

  const t = (key: string, params?: Record<string, string | number> | string, fallbackEn?: string): string => {
    let fallback: string | undefined;
    let vars: Record<string, string | number> | undefined;

    if (typeof params === 'string') {
      fallback = params;
    } else if (params) {
      vars = params;
      fallback = fallbackEn;
    }

    let text = translations[key]?.[lang];
    if (!text) {
      if (lang === 'en' && fallback) {
        text = fallback;
      } else {
        text = translations[key]?.cs ?? fallback ?? key;
      }
    }

    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
